[#_跨度查询]
=跨度查询

xref:_SpanTerm查询[span_term]

- 等同于 xref:./TermLevelQueries.adoc#_term查询[term查询]，但用于其它跨度查询。

xref:_SpanMulti查询[span_multi]

- 包括 xref:./TermLevelQueries.adoc#_term查询[term]、xref:./TermLevelQueries.adoc#_range查询[range]、xref:./TermLevelQueries.adoc#_prefix查询[prefix]、xref:./TermLevelQueries.adoc#_wildcard查询[wildcard]、xref:./TermLevelQueries.adoc#_regexp查询[regexp] 或 xref:./TermLevelQueries.adoc#_fuzzy查询[fuzzy]。

xref:_SpanFirst查询[span_first]

- 在前N个位置接受其它跨度查询。

xref:_SpanNear查询[span_near]

- 在指定距离内接受其它跨度查询，并且可以是以相同的顺序。

xref:_SpanOr查询[span_or]

- 将多个跨度查询组合起来，并返回任何匹配的文档。

xref:_SpanNot查询[span_not]

- 包含其它跨度查询，并排除匹配的文档。

xref:_SpanContaining查询[span_containing]

- 接受一个跨度查询列表，但只返回于两个条件都匹配的文档。

xref:_SpanWithin查询[span_within]

- 只要跨度落在由其它跨度范围中，就会返回一个跨度查询的结果。


[#_SpanTerm查询]
==SpanTerm查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-term-query.html[Span Term Query]

[source,java]
----
spanTermQuery(
        "user",
        "kimchy");
----

[#_SpanMulti查询]
==SpanMulti查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-multi-term-query.html[Span Multi Term Query]

[source,java]
----
spanMultiTermQueryBuilder(
        //支持任何继承MultiTermQueryBuilder的类。例如：FuzzyQueryBuilder、PrefixQueryBuilder、RangeQueryBuilder、RegexpQueryBuilder或WildcardQueryBuilder
        prefixQuery("user", "ki"));
----

[#_SpanFirst查询]
==SpanFirst查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-first-query.html[Span First Query]

[source,java]
----
spanFirstQuery(
        spanTermQuery("user", "kimchy"),
        //最大位置
        3
    );
----

[#_SpanNear查询]
==SpanNear查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-near-query.html[Span Near Query]

[source,java]
----
spanNearQuery(
        spanTermQuery("field","value1"),
        //不匹配的最大数量
        12)
            .addClause(spanTermQuery("field","value2"))
            .addClause(spanTermQuery("field","value3"))
            //是否按照顺序进行匹配
            .inOrder(false);
----

[#_SpanOr查询]
==SpanOr查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-or-query.html[Span Or Query]

[source,java]
----
spanOrQuery(spanTermQuery("field","value1"))
    .addClause(spanTermQuery("field","value2"))
    .addClause(spanTermQuery("field","value3"));
----

[#_SpanNot查询]
==SpanNot查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-not-query.html[Span Not Query]

[source,java]
----
spanNotQuery(
        spanTermQuery("field","value1"),
        spanTermQuery("field","value2"));
----

[#_SpanContaining查询]
==SpanContaining查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-containing-query.html[Span Containing Query]

[source,java]
----
spanContainingQuery(
        spanNearQuery(spanTermQuery("field1","bar"), 5)
            .addClause(spanTermQuery("field1","baz"))
            .inOrder(true),
        spanTermQuery("field1","foo"));
----

[#_SpanWithin查询]
==SpanWithin查询

查看 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-span-within-query.html[Span Within Query]

[source,java]
----
spanWithinQuery(
        spanNearQuery(spanTermQuery("field1", "bar"), 5)
            .addClause(spanTermQuery("field1", "baz"))
            .inOrder(true),
        spanTermQuery("field1", "foo"));
----
